services:
  - type: web
    name: teamquiz
    env: python
    plan: free
    buildCommand: |
      # Install only backend dependencies (frontend build already included)
      pip install -r requirements.txt
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: NODE_VERSION  
        value: 18
    disk:
      name: teamquiz-disk
      mountPath: /opt/render/project/src
      sizeGB: 1